# File Name: config.yaml
# Created By: ZW
# Created On: 2021-05-06
# Purpose: configuration file for running MANTA SV caller on WGS from 1000 Genomes

# directory definitions
working_dir : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/
tmp : /home/zweber/scratch-midway2/SV-calling/
data_dir : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/data/toydata/
results_dir : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/results/

reference_fasta : /home/zweber/reference/GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa
sample_file : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/data/toydata/samples.tsv
call_regions : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/resources/callregions.sorted.bed.gz
tad_boundaries : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/resources/GHselectedTADS.boundaries.lexsort.hg38.bed
genome_file : /project2/nobrega/zach/Identifying-TAD-boundary-Disruptions/resources/chrom.sizes.hg38

# conda environment definitions
conda :
    manta : configs/manta-env.yaml
    samtools : configs/samtools-env.yaml

# rule-specific parameters
rule_params :
    samtools :
        threads : 4
    manta :
        jobs : 8
        memGB : 8
    bedtools :
        evidence_roi_margin : 1000
